version: '3'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: "todos"
      POSTGRES_USER: "todosapi"
      POSTGRES_PASSWORD: "todosapi"
    ports:
      - 5432:5432
    expose:
      - 5432
  api:
    build:
      context: .
    image: kidsan/todo-api:develop
    environment:
     - DATABASE_HOST=database
    ports:
      - 3000:3000